dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
after_success:
  - bash ci/after_success.sh
cache:
  directories:
    - "$HOME/.m2"
deploy:
  - provider: script
    script: bash ci/deploy-snapshot.sh
    on:
      repo: dropwizard/dropwizard-cassandra
      tags: false
      branch: master
      jdk: openjdk8
  - provider: script
    script: bash ci/deploy-release.sh
    on:
      repo: dropwizard/dropwizard-cassandra
      tags: true
      jdk: openjdk8
env:
  global:
    - secure: vTRbTgR2eBzzHUtgrMKkgSunvF2KwCU6Nfb9V8QGPmE7Wo4GH7aU5v3ADYtyRE4BYOandmHvaPZ6RlaKPwVxGX9cH71xCLmrI7htewLTrCqhu4TGWbnLwA83Jstchxf0vuoYGLd48ypCzf1Bfby9N/44EgNuaqAaOMBhDH0Mhq61bsJfwVqivRzPKWOSZHjd+8zZeXGGbBXEKMeUiGrx8zhdPyM3kAmW6nig66DV4rH4dQQXV1VcVWu3W7APc6oBjU6dHCI1dxf0bKM2VkVE+kJcbb1AQy6RWyx9DRaC8Z8Kbr06ubSJdJRp5Pc5KAvAAZgpMtiJJYPsDipiX1sj4yAxTIMFbD5hyoakLslFwgyHSBxYjeSqR0P9i9XSTfY+DdV4pHKj1IAUSM13t4h7MRdtrehQ27kOWLyB6V9efZcmclSyC7b13ETD3zuBOC9YKkLzwMQbeuwNq5YgKJwazZg4FR4yrSXwEzxtwSfRPhbwTTgZaoOUOOTGmZH3J9bPMTD2Z/raC7EENOaGOPI93nPu4oOgaadGuop1kwkPZLHL0ghfWPm7XrZnN4A2KLBW1GUXAHZgWu3bSuEAGxXUL0YD9QReMhVMeQ7R7iQUQOXWfIofW6vo+TxAOqSTDhyl9lyPkTUf4+JopGdqcz2NK76RMI+jmSOD0KEZIzLW8Rk=
    - secure: NedahIWncI7m9M1QeuSPwuxXYUbwCiJtkQe1dXk1svsZtYBFeJJh98LM+ilV+mEX0TX/iL8hQA/QOa0lXX/2L/OMaxx+bNnu3bmhcWhj5ZpR0+YFOX6+EE4qTz3B+wK9ww53dtS1rHSgs6YJLPB8n3zw4m9IKUX3X/1oFwTO4WbUeZxIFm+Ws8Wn6tSU2vz9z7KJc/+OFz4f21NeP0avDTUfAUmcJFIWOL7rlhOMu3lJ/EZ/kMq30ra+nIryDJI8CVIxsQLcaMaFmuJMMZe/QlnMnNWRVz7kLayO7OO+JKNvNERLwQZTOK8KpEdjbf2Uwwjcw9YvwSMeRO13w4lISLhjgoBTE1ggEiG+R0O/VJ6Rj0Fs2gJyGs06jYcBySisvATaTQ0oX1bcLOYKPRqDzB7y+9+oJzpaEmo3LTcRHWw7mzMzjaxZD2VL/UKguhAILnC7A60tgql9IgmZpGZ+Ph5Cgv8gRMpyEXKy8GRhI/wnNsY/h9qOr2PnO63RbBLL+mfNbsX8F/qlZ/NSdEqCKtZNpeCcAqCvDBxlauof56tWJ1ULHdLgfdy1IYptSBqbLP1gwLYXwkrH4nj4B15vmhWRcZMe9wlhXUk5/oFyWcz1bfX0vYmyxG5GV9+Am05W+2iZvV1lPWDSB9Iqc7y6iYjuxILc/7l89e1fxF0H+OA=
